Add support for material-icons
mpetuska/kmdc pull request #40
Opened 2021-12-14 19:17 UTC by pocharlebois

* Based on the npm https://github.com/marella/material-icons
* All material icons as of 1.10.4 in an enum - ie: pie_chart ->
  PieChart("pie_chart") in MDCIconOpts.MDCIconType
* Numbers written out using Proper Case 1MP -> OneMp
* Output is a Span with the right class (Filled, Outlined, TwoTone, etc)
* As elsewhere in KMDC, styling has to be applied externally

Addresses #33

2021-12-15 09:25 UTC, mpetuska requested changes
Great work. Left some minor comments for you to address.

2021-12-15 09:25 UTC, mpetuska commented on README.md
> +- [x] material-icon
`icons` plural

2021-12-15 09:25 UTC, mpetuska commented on lib/kmdc-icon/build.gradle.kts
> +import de.fayard.refreshVersions.core.versionFor
Rename module to be kmdc-icons (plural) to match npm library

2021-12-15 09:25 UTC, mpetuska commented on lib/kmdc-icon/build.gradle.kts
> +val mdcIconVersion = versionFor("version.npm.material-icons")
Move this to line 13 (inside dependencies block) since it's only required there.

2021-12-15 09:25 UTC, mpetuska commented on lib/kmdc-icon/src/jsMain/kotlin/MDCIcon.kt
> +public fun MDCIcon(opts: Builder<MDCIconOpts>? = null) {
Add KDoc comment to direct link of js api (see how other modules are done) of a particular material-icons tag in gh

2021-12-15 09:25 UTC, mpetuska commented on lib/kmdc-icon/src/jsMain/kotlin/MDCIcon.kt
> +    Filled("material-icons"), Outlined("material-icons-outlined"), Round("material-icons-round"), Sharp("material-icons-sharp"), TwoTone("material-icons-two-tone")
This line is too long, place each item on a separate line.

2021-12-15 14:04 UTC, mpetuska requested changes
Almost there :)

2021-12-15 14:04 UTC, mpetuska commented on lib/kmdc-icons/src/jsMain/kotlin/MDCIcon.kt
> + * [JS API](https://github.com/marella/material-icons)
Sorry to be so picky, but since kotlin is yet another layer on top of npm dependency, it's quite likely that we won't always be on the latest npm dependecy version, so the link needs to be more specific, pointing to a concrete tag. 

Change link to `https://github.com/marella/material-icons/tree/v1.10.4` and version in versions.properties to `^1.10.4`

2021-12-15 14:06 UTC, mpetuska commented
As a side note, it would be good if you could stop force-pushing as it often messes up github links, even for linear history. Not a deal-breaker otherwise.

2021-12-15 22:27 UTC, pocharlebois commented on lib/kmdc-icons/src/jsMain/kotlin/MDCIcon.kt
> + * [JS API](https://github.com/marella/material-icons)
Don't ever feel sorry for being picky on code reviews, even more so when they are aimed at contributing to the open source community ;) On the contrary, thanks for teaching me better practices.

2021-12-16 09:45 UTC, mpetuska requested changes

2021-12-16 09:45 UTC, mpetuska commented on lib/kmdc-icons/src/jsMain/kotlin/MDCIcon.kt
> +public fun MDCIcon(opts: Builder<MDCIconOpts>? = null) {
Oof, missed it first time around, but since we're wrapping a single html element, it's always a good practice to expose attrs and content builder functions. Have a look at MDCButton for an example how it's done ;)

2021-12-16 14:55 UTC, rocketraman commented
> As a side note, it would be good if you could stop force-pushing as it often messes up github links, even for linear history. Not a deal-breaker otherwise.

Sorry @mpetuska our internal workflow for branches is to force push them to keep the history clean. Would you prefer "fixup!" and "squash!" commits during the review process with a final rebase before merge, or do you prefer branches keep a simple linear history, mistakes and all?

2021-12-16 15:14 UTC, mpetuska commented
Well I'm squashing all commits when merging pr anyways to keep pr to commit ratio consistent on master. Not force-pushing to pr branches would make gh permalinks less flakey. But as I said before, this is not a deal breaker, but just my preference.

2021-12-16 16:28 UTC, mpetuska commented
But I'm happy to ignore `base` opt as this stage as it can be enhanced later. I'll leave it up to you to decide when you want to merge this.

2021-12-16 17:54 UTC, rocketraman commented
> But I'm happy to ignore `base` opt as this stage as it can be enhanced later. I'll leave it up to you to decide when you want to merge this.

I suspect @pocharlebois would rather merge this as-is, and leave the `base` opt for later enhancement.

2021-12-16 18:00 UTC, merged