kmdc-icons: allow to use span or i tag for material icons
mpetuska/kmdc pull request #42
Opened 2021-12-17 02:28 UTC by pocharlebois

* A new MDCIconBase type allows the user so use either
  a default SPAN tag or the valid I tag to display
  the selected material icon.

2021-12-17 09:40 UTC, mpetuska requested changes
This works, but there are some improvements to be made.

2021-12-17 09:40 UTC, mpetuska commented on lib/kmdc-icons/src/jsMain/kotlin/MDCIcon.kt
> +public fun MDCIcon(opts: Builder<MDCIconOpts>? = null, attrs: AttrBuilderContext<*>? = null) {
Instead of `AttrBuilderContext<*>` use common denominator `AttrBuilderContext<HTMLElement>`

2021-12-17 09:40 UTC, mpetuska commented on lib/kmdc-icons/src/jsMain/kotlin/MDCIcon.kt
> +public fun MDCIcon(opts: Builder<MDCIconOpts>? = null, attrs: AttrBuilderContext<*>? = null) {
It would be nice to also have specialised inline DSL for `MDCIconSpan` and `MDCIconI` that has more specific attr builder type and calls into this function.

2021-12-18 02:19 UTC, pocharlebois commented on lib/kmdc-icons/src/jsMain/kotlin/MDCIcon.kt
> +public fun MDCIcon(opts: Builder<MDCIconOpts>? = null, attrs: AttrBuilderContext<*>? = null) {
I went the other way around by defining the actual implementation in MDCIconSpan and MDCIconI in their respective function and using the MDCIcon as the router.

2021-12-18 14:49 UTC, mpetuska approved these changes
Still some improvements to be made.

2021-12-18 14:49 UTC, mpetuska commented on lib/kmdc-icons/src/jsMain/kotlin/MDCIcon.kt
> +  attrs: AttrBuilderContext<out HTMLElement>? = null)
Builder here can now be more specific `HTMLSpanElement`. Also `out` keyword is not needed here. (have a look at what exact argument `Span{}` takes)

2021-12-18 14:49 UTC, mpetuska commented on lib/kmdc-icons/src/jsMain/kotlin/MDCIcon.kt
> +  attrs: AttrBuilderContext<out HTMLElement>? = null)
See if there's a more specific `HTMLIElement` (have a look at what exact argument `I{}` takes).

2021-12-18 14:49 UTC, mpetuska commented on lib/kmdc-icons/src/jsMain/kotlin/MDCIcon.kt
> +    MDCIconOpts.MDCIconBase.Span -> MDCIconSpan(opts, attrs)
To enable changes requested above, attrs will need to be (unsafe) casted when routing to proper implementation. Additionally, the function could be made inline.

2021-12-18 15:28 UTC, rocketraman commented on lib/kmdc-icons/src/jsMain/kotlin/MDCIcon.kt
> +  attrs: AttrBuilderContext<out HTMLElement>? = null)
Unfortunately `I { }` takes a `AttrsBuilder<HTMLElement>`, not an `AttrsBuilder<HTMLIElement>`. Not sure why.

2021-12-18 15:28 UTC, rocketraman commented on lib/kmdc-icons/src/jsMain/kotlin/MDCIcon.kt
> +    MDCIconOpts.MDCIconBase.Span -> MDCIconSpan(opts, attrs)
What is the advantage of making this `inline`? IDEA reports the expected perf impact of inlining to be negligible due to the lack of functional type parameters.

For some reason (and I have to admit I'm not sure why, because it doesn't seem like it should work) the cast is not necessary if the type parameter of `AttrBuilderContext` has `out` variance. See 6f32ee6.

2021-12-18 16:00 UTC, mpetuska approved these changes

2021-12-18 16:00 UTC, merged

2021-12-18 16:01 UTC, mpetuska commented on lib/kmdc-icons/src/jsMain/kotlin/MDCIcon.kt
> +    MDCIconOpts.MDCIconBase.Span -> MDCIconSpan(opts, attrs)
Well both, opts and attrs are lambdas