Introduce collision-free DOM IDs (fix #65)
mpetuska/kmdc pull request #66
Opened 2021-12-31 15:24 UTC by OliverO2

@mpetuska Could you do me a favor and not squash commits? This allows me to keep track of what's merged.

2021-12-31 15:27 UTC, mpetuska commented
How do you mean? Commits are only squashed on merge, so you're free to push to your feature branch however you prefer.

2021-12-31 15:30 UTC, mpetuska requested changes

2021-12-31 15:30 UTC, mpetuska commented on kmdc/kmdc-core/src/jsMain/kotlin/util.kt
> +public fun uniqueDomElementId(): String = "kmdc-${nextDomElementId++}"
Might as well change it to a `val uniqueDomElementId get() = "kmdc-${nextDomElementId++}"`

2021-12-31 15:30 UTC, mpetuska commented on kmdc/kmdc-textfield/src/jsMain/kotlin/MDCTextArea.kt
> +  val helperId = remember { uniqueDomElementId() }
reuse labelId here to build helperId instead of incrementing ID fatory twice.

2021-12-31 15:30 UTC, mpetuska commented on kmdc/kmdc-textfield/src/jsMain/kotlin/MDCTextField.kt
> +  val helperId = remember { uniqueDomElementId() }
Same as before, unnecessary increment to id factory.

2021-12-31 15:48 UTC, OliverO2 commented on kmdc/kmdc-core/src/jsMain/kotlin/util.kt
> +public fun uniqueDomElementId(): String = "kmdc-${nextDomElementId++}"
While functionally equivalent, I'd prefer the `fun` here as it emphasizes that a new value is generated per invocation.

2021-12-31 15:53 UTC, OliverO2 commented on kmdc/kmdc-textfield/src/jsMain/kotlin/MDCTextArea.kt
> +  val helperId = remember { uniqueDomElementId() }
These are independent entities, so the code seems simpler to comprehend when not coupling them. What's the downside of incrementing twice?

2021-12-31 15:56 UTC, OliverO2 commented
On squashing commits: When I work on multiple branches and create separate PRs from those, it gets very messy when merging back from upstream. I won't see which commits actually landed in upstream, and which ones I might have forgotten to put in the right branch to be included in a PR.

2022-01-01 14:34 UTC, mpetuska commented on kmdc/kmdc-textfield/src/jsMain/kotlin/MDCTextArea.kt
> +  val helperId = remember { uniqueDomElementId() }
They're not that independent, because they both belong to the same MDC component. For clarity you could do something like this:
```kotlin
val localId = remember { uniqueDomElementId() }
val labelId = "$localId-label"
val helperId = "$localId-helper"
```

I'm trying to limit the increments to the id factory as it's not unlimited and can eventually overflow.

2022-01-01 14:36 UTC, mpetuska commented on kmdc/kmdc-textfield/src/jsMain/kotlin/MDCTextArea.kt
> +  val helperId = remember { uniqueDomElementId() }
I'm aware that the buffer is insanely large, but it's just a good practice to not abuse it where possible. Also having shared ID between related components will help with DOM readability.

2022-01-01 14:40 UTC, mpetuska commented
RE: Squashing

I'm still not convinced. Don't take it the wrong way, but I think master branch readability in any OSS project is more important than meeting any singe contributor's workflow. 

It's probably not what you expected to hear back, but can I suggest not spreading yourself too thin and limit working on one or two issues at any given time. I do my best to be as responsive with PRs as I can, so that you wouldn't have them stewing and blocking you for too long. Additionally, all squashed commit messages are included into squash commit message, so you can have a look at those if you need a refresher of what's landed in master.

2022-01-01 23:05 UTC, OliverO2 commented on kmdc/kmdc-textfield/src/jsMain/kotlin/MDCTextArea.kt
> +  val helperId = remember { uniqueDomElementId() }
I guess we're agreeing that the ID space is large enough to be safe for all practical purposes. That would leave no room for any kind of "abuse". The "ID generator" could even be used freely by others without any downside.

On semantic coupling by postfixing a common ID: As the entire structure might change later on, no one should interpret anything specific into those IDs. Actually, there is a bug in the previous code where a prefix is applied twice, breaking the ARIA label reference.

So I'd stick with decoupling, safe and simple. If you still disagree, feel free to apply changes as you see fit.

2022-01-01 23:07 UTC, OliverO2 commented
OK, different preferences here. I'm following the original Linux kernel style, where they never squash commits. Some aspects are [explained here](https://www.kernel.org/doc/html/latest/maintainer/rebasing-and-merging.html).

> If you have pulled changes from another developer’s repository, you are now a custodian of their history. You should not change it.

Of course, this is your repository. I can only point out that squashing commits comes at a price.

Another consequence, while not relevant for me, is that contributors will be disadvantaged in the GitHub committer statistics, when a series of maintainer commits is preserved 1:1, while a series of contributor commits will be squashed n:1.

2022-01-02 11:00 UTC, mpetuska commented
I see. Your second point raises some concerns. Let me stew on this for a while before I make any decisions.

2022-01-02 11:01 UTC, merged

2022-01-02 22:32 UTC, OliverO2 commented
If you are mainly concerned with GitHub statistics, that could be alleviated by using PRs with squashed commits for your own series of changes.

I can understand that a GitHub history with less noise would be ideal, but that seems hard to maintain in practice without losing information where it matters most: Most people tend to look no further than commit summary lines when reviewing Git history, as this is what most tools present.

Now let's say, someone starts to work on a change, then discovers a related issue, improves documentation and tweaks the build system. Often, such changes warrant a distinct commit message each, which would be lost in (summary line) history if squashed into one overarching commit.

An example, though probably not resulting from squashing, is 8663bed516db6722e1c3ba57278a0f22644b60d8, which suggests it deals with "contributing guidelines", but also changes the build system, adds tests, reconfigures Webpack, adds Sass and others.

Often there is a trade-off between losing important information in (summary line) history, or having to skip the occasional "fix typo" or "chore" commit.

2022-01-03 03:36 UTC, mpetuska commented
I do raise PRs for most of my changes, although I must admit there have been quite a few "cleanup" commits unrelated to any particular issue that I've pushed straight to master.

As for details lost, my thinking is that if all changes go through PRs, they would have all the details in much more descriptive manner including comments and PR discussions. With all that, commit summary cannot even come close to that kind of comtext and squashing commits always leaves a reference to relevant PR.

2022-01-03 18:48 UTC, OliverO2 commented
I have tried to find some data on merge strategies and looked at a non-representative sample of projects. It seems that more recent projects tend to favor squashing commits on PRs. The same projects show micro-commits from maintainers, which would most probably be squashed if coming in via PRs.

Conclusions:
1. For contributors, the PR is the new commit.
2. For maintainers, different rules apply.
3. The "clean history" objective is not pursued consistently.
4. GitHub commit statistics are heavily biased towards maintainers.

For me, point 4 does not really matter as GitHub's commit and line count statistics seem pretty meaningless anyway. However, folks trying to impress potential employers might think differently.

There seems to be a lack of research on the consequences of choosing a commit strategy. I could not find any data about a strategy's potential of supporting specific workflows or encouraging specific types/sizes of contributions.

Regarding details lost, I agree that additional commit message lines and collateral like issue and PR discussions are valuable. I'd just be missing a compact yet complete, detailed changelog, which an unsquashed list of commit summary messages could provide (if done sensibly).

2022-01-03 19:59 UTC, mpetuska commented
I'm maintaining a separate changelog in the repo to track changes feature wise. As for disparity between contributors and maintainers, I've just protected master branch to prevent direct pushes from anyone (including admins) so that anyone working on this repo would be on an equal footing.