kmdc-menu and kmdc-menu-surface
mpetuska/kmdc pull request #67
Opened 2022-01-05 15:36 UTC by pocharlebois

Provides support for MDCMenu and MDCMenuSurface
Demonstrate use as a dropdown in Sandbox

Fixes #18 and #19

2022-01-05 17:49 UTC, mpetuska requested changes
Some work needed. I recommend reviewing MDC docs with a fresh set of eyes as well as having a look at newer KMDC modules to get a feel at how wrapping should be done.

2022-01-05 17:49 UTC, mpetuska commented on kmdc/kmdc-menu-surface/src/jsMain/kotlin/MDCMenuSurface.kt
> +  public var style: Style = Style.Default,
This is incorrect. `mdc-menu-surface--anchor` is a separate element that can be used as a parent to `mdc-menu-surface` element to anchor its position and contain other "visible" items. mdc-menu-surface should only have a single opt - `fixed: Boolean = false`.

2022-01-05 17:49 UTC, mpetuska commented on kmdc/kmdc-menu-surface/src/jsMain/kotlin/MDCMenuSurface.kt
> +public external val MDCMenuSurfaceStyle: dynamic
Styles should be kept private

2022-01-05 17:49 UTC, mpetuska commented on kmdc/kmdc-menu-surface/src/jsMain/kotlin/MDCMenuSurface.kt
> +package dev.petuska.kmdc.menu
Missing `MDCMenuAnchor` composable

2022-01-05 17:49 UTC, mpetuska commented on kmdc/kmdc-menu-surface/src/jsMain/kotlin/MDCMenuSurface.kt
> +    classes(*options.style.classes)
Missing JS module declaration and instantiation.

2022-01-05 17:49 UTC, mpetuska commented on sandbox/src/jsMain/kotlin/samples/Menu.s.kt
> +private val MenuSamples = Samples("MDCMenu") {
Would be good to showcase and test the other three variations - default, fixed and absolute

2022-01-05 17:49 UTC, mpetuska commented on kmdc/kmdc-menu/src/jsMain/kotlin/MDCMenuList.kt
> +public external val MDCMenuStyle: dynamic
Styles should be private

2022-01-05 17:49 UTC, mpetuska commented on kmdc/kmdc-menu/src/jsMain/kotlin/MDCMenuList.kt
> +  initialize: (
This arg should not be exposed to public API and instead be handled internally

2022-01-05 17:49 UTC, mpetuska commented on kmdc/kmdc-menu/src/jsMain/kotlin/MDCMenuList.kt
> +  Div(attrs = {
Reuse MDCMenuSurface composable and append missing attributes instead of redeclaring div again.

2022-01-05 17:49 UTC, mpetuska commented on kmdc/kmdc-menu/src/jsMain/kotlin/MDCMenuList.kt
> +  public class MDCMenu(element: Element) {
Implement `Destroyable` interface.

2022-01-05 17:49 UTC, mpetuska commented on kmdc/kmdc-menu/src/jsMain/kotlin/MDCMenuList.kt
> +    ref {
Since MDCMenu is Detroyable, this entire ref block can be replaced with `initialiseMDC()`

2022-01-05 17:49 UTC, mpetuska commented on kmdc/kmdc-menu/src/jsMain/kotlin/MDCMenuList.kt
> +  var onSelected: (Int) -> Unit = {}
event handlers are not opts. If you want provide event wrappers, have a look at how they're exposed in kmdc-slider.

2022-01-05 17:49 UTC, mpetuska commented on kmdc/kmdc-menu/src/jsMain/kotlin/MDCMenuList.kt
> +    addEventListener("MDCMenu:selected") {
Should be removed

2022-01-05 17:49 UTC, mpetuska commented on kmdc/kmdc-menu/src/jsMain/kotlin/MDCMenuList.kt
> +      attr("role", "menu")
Use `role("menu")` instead

2022-01-05 17:49 UTC, mpetuska commented on kmdc/kmdc-menu/src/jsMain/kotlin/MDCMenuList.kt
> +      content?.let { MDCMenuListScope(this).it() }
Move content out of this lambda and into MDCList argument.

2022-01-05 17:49 UTC, mpetuska commented on kmdc/kmdc-menu/src/jsMain/kotlin/MDCMenuList.kt
> +package dev.petuska.kmdc.menu
File should be renamed to match main composable - MDCMenu.kt

2022-01-05 17:49 UTC, mpetuska commented on kmdc/kmdc-menu/src/jsMain/kotlin/MDCMenuList.kt
> +public class MDCMenuListScope<T : HTMLElement>(public val listScope: MDCListScope<T>) : ElementScope<T> by listScope
Rename to MDCMenuScope and remove generic argument.

2022-01-05 17:49 UTC, mpetuska commented on kmdc/kmdc-menu/src/jsMain/kotlin/MDCMenuItem.kt
> +package dev.petuska.kmdc.menu
File should be renamed to MDCMenuItem.kt

2022-01-05 17:49 UTC, mpetuska commented on kmdc/kmdc-menu/src/jsMain/kotlin/MDCMenuItem.kt
> +public data class MDCMenuListItemOpts(
Rename all MDCMenuListItem* to MDCMenuItem*

2022-01-05 17:49 UTC, mpetuska commented on kmdc/kmdc-menu/src/jsMain/kotlin/MDCMenuItem.kt
> +public data class MDCMenuListItemOpts(
Opts are not needed here as we can reuse MDCListItemOpts

2022-01-05 17:49 UTC, mpetuska commented on kmdc/kmdc-menu/src/jsMain/kotlin/MDCMenuItem.kt
> +    options.text?.let { Span({ classes("mdc-deprecated-list-item__text") }) { Text(it) } }
Remove this opt. The consumers should reuse MDCList* where relevant.

2022-01-06 03:29 UTC, pocharlebois commented on kmdc/kmdc-menu/src/jsMain/kotlin/MDCMenuList.kt
> +      attr("role", "menu")
Could not find role() so I kept attr("role", "")

2022-01-06 04:33 UTC, pocharlebois commented on kmdc/kmdc-menu/src/jsMain/kotlin/MDCMenuList.kt
> +public class MDCMenuListScope<T : HTMLElement>(public val listScope: MDCListScope<T>) : ElementScope<T> by listScope
@mpetuska I'm not having success with the two outstanding comments regarding scope handling. Would you mind helping cleaning that up? Apart from that, I think the recent refactor better aligned the kmdc-menu with your more recent components.

2022-01-06 09:16 UTC, mpetuska commented on kmdc/kmdc-menu/src/jsMain/kotlin/MDCMenuList.kt
> +      attr("role", "menu")
https://github.com/mpetuska/kmdc/blob/master/kmdc/kmdc-core/src/jsMain/kotlin/attrs.kt#L12

2022-01-06 10:05 UTC, mpetuska requested changes
Much better this time around.

P.S. Conversations should be resolved by their author, not comitter. Also I'd very much appreciate if you could resist force-pushes as it invalidates some review history for me and makes incremental reviews harder.

2022-01-06 10:07 UTC, mpetuska commented on kmdc/kmdc-menu/src/jsMain/kotlin/MDCMenuList.kt
> +public class MDCMenuListScope<T : HTMLElement>(public val listScope: MDCListScope<T>) : ElementScope<T> by listScope
`public class MDCMenuListScope(scope: ElementScope<HTMLUlElement>) : MDCListScope<HTMLUlElement>(scope)`

2022-01-06 19:14 UTC, pocharlebois commented on kmdc/kmdc-menu-surface/src/jsMain/kotlin/MDCMenuSurface.kt
> +  }) {
The content attribute on the AttrsBuilder<HTMLDivElement> is a val and cannot be assigned. We need to invoke in the body.

2022-01-06 19:17 UTC, pocharlebois commented on sandbox/src/jsMain/kotlin/samples/Menu.s.kt
> +private val MenuSamples = Samples("MDCMenu") {
I created a menu with setAbsolutionPosition and a Dropdown anchored on a text field.

2022-01-06 19:18 UTC, pocharlebois commented on kmdc/kmdc-menu/src/jsMain/kotlin/MDCMenuList.kt
> +public class MDCMenuListScope<T : HTMLElement>(public val listScope: MDCListScope<T>) : ElementScope<T> by listScope
I believe I have correctly setup the scopes in my last commit. Please verify

2022-01-06 19:18 UTC, pocharlebois commented on kmdc/kmdc-menu-surface/src/jsMain/kotlin/MDCMenuAnchor.kt
> +public class MDCMenuSurfaceAnchorScope(scope: ElementScope<HTMLDivElement>) :
removed

2022-01-06 19:29 UTC, pocharlebois commented
@mpetuska I did another pass which should resolve all pending issues.

2022-01-07 09:59 UTC, mpetuska requested changes
Some new things to look into as well as some things remaining unresolved from the previous review.

2022-01-07 09:59 UTC, mpetuska commented on kmdc/kmdc-menu-surface/src/jsMain/kotlin/MDCMenuAnchor.kt
File should match main composable - `MDCMenuSurfaceAnchor.kt`

2022-01-07 09:59 UTC, mpetuska commented on kmdc/kmdc-menu-surface/src/jsMain/kotlin/MDCMenuAnchor.kt
> +    content?.invoke(this)
Why was this moved out of Div arguments?

2022-01-07 09:59 UTC, mpetuska commented on kmdc/kmdc-menu-surface/src/jsMain/kotlin/constants.kt
> +public enum class Corner(@Suppress("UNUSED_PARAMETER ") corner: Byte) {
What's the point of having unused constructor parameter here?

2022-01-07 09:59 UTC, mpetuska commented on kmdc/kmdc-menu-surface/src/jsMain/kotlin/MDCMenuSurface.kt
> +public class MDCMenuSurfaceAttrsScope private constructor() : AttrsBuilder<HTMLDivElement>()
Does MDCMenuSurface have any custom event which warrants this custom attrs scope?

2022-01-07 09:59 UTC, mpetuska commented on kmdc/kmdc-menu-surface/src/jsMain/kotlin/MDCMenuSurface.kt
> +  }) {
Since the style is now applied above, this simple content builder can be moved into Div arguments.

2022-01-07 09:59 UTC, mpetuska commented on sandbox/src/jsMain/kotlin/samples/Menu.s.kt
>  import dev.petuska.kmdc.textfield.MDCTextFieldCommonOpts
Make MenuSamples private

2022-01-07 09:59 UTC, mpetuska commented on kmdc/kmdc-menu/src/jsMain/kotlin/events.kt
> +public fun MDCMenuAttrsScope.onSelected(listener: (event: MDCMenuModule.MDCMenuSelectedEvent) -> Unit) {
Let's rename it to something like `onMenuItemSelected` to avoid ambiguity and potential clashes with standard DOM event names.

2022-01-07 14:09 UTC, pocharlebois commented on kmdc/kmdc-menu/src/jsMain/kotlin/events.kt
> +public fun MDCMenuAttrsScope.onSelected(listener: (event: MDCMenuModule.MDCMenuSelectedEvent) -> Unit) {
I can do that. However, I'm wondering if we should keep the Material io API name which is "selected" to be consistent.

2022-01-07 14:11 UTC, mpetuska commented on kmdc/kmdc-menu/src/jsMain/kotlin/events.kt
> +public fun MDCMenuAttrsScope.onSelected(listener: (event: MDCMenuModule.MDCMenuSelectedEvent) -> Unit) {
Yeah, it's a double-edge sword... Ok, leave it as-is for now and I'll review it closer to 0.1.0 release when I'll be reviewing all events.

2022-01-07 19:16 UTC, pocharlebois commented on kmdc/kmdc-menu-surface/src/jsMain/kotlin/constants.kt
> +public enum class Corner(@Suppress("UNUSED_PARAMETER ") corner: Byte) {
After research, the best would be to have include the definition from @material/menu-surface/constants. However, the ability to use `public enum class Corner { TOP_LEFT, ... }` will we part of 1.6.20-M1 (https://youtrack.jetbrains.com/issue/KT-37916) so I've defined the class next to it and we can refactor once available.

2022-01-07 19:18 UTC, pocharlebois commented on kmdc/kmdc-menu/src/jsMain/kotlin/MDCMenuList.kt
> +      attr("role", "menu")
I extended the generic for Role to include all HTMLElement (was HTMLButtonElement)

2022-01-08 15:03 UTC, mpetuska requested changes
Almost there. Main leftover concern is `Corner` "enum"

2022-01-08 15:04 UTC, mpetuska commented on kmdc/kmdc-menu-surface/src/jsMain/kotlin/MDCMenuSurface.kt
> +  content: ComposableBuilder<ElementScope<HTMLElement>>? = null,
Or maybe it's `ElementBuilder`? Can;t remember, just check how `Div` arguments are typed.

2022-01-09 00:16 UTC, mpetuska approved these changes
We got there in the end. There are still few minor inconsistencies, but I can sort them out myself during final pre-0.1.0 review. Thanks!

2022-01-09 00:16 UTC, merged