Add support for MDCMenuSurface closed, closing, and opened events.
mpetuska/kmdc pull request #72
Opened 2022-01-11 05:04 UTC by gsteckman

Addresses #70 by adding support for the closed event. The event is fundamentally for the MDCMenuSurface class, but since the Composable MDCMenu uses MDCMenuSurface internally, therefore hiding it from callers, the events were also exposed in MDCMenuAttrsScope.

2022-01-11 10:02 UTC, mpetuska requested changes
Good job. Left few minor comments for improvements.

2022-01-11 10:02 UTC, mpetuska commented on kmdc/kmdc-menu/src/jsMain/kotlin/events.kt
> +  addEventListener(MDCMenuSurfaceModule.strings.CLOSED_EVENT, listener)
unsafeCast attrs scope and reuse event DSL from menu-surface.

2022-01-11 10:02 UTC, mpetuska commented on sandbox/src/jsMain/kotlin/samples/Menu.s.kt
> +    onClosed { menuOpen = false }
Just curious, wouldn't this event get fired together with `onSelected` as well? If so, no use in duplicating menuOpen state control and oClosed alone should be sufficient.

2022-01-11 10:09 UTC, mpetuska commented on kmdc/kmdc-menu/src/jsMain/kotlin/events.kt
> +  addEventListener(MDCMenuSurfaceModule.strings.CLOSED_EVENT, listener)
Or even better yet, make MDCMenuAttrsScope class extend MDCMenuSurfaceAttrsScope class and remove these DSLs.

2022-01-12 09:13 UTC, mpetuska requested changes
Sorry, missed one more thing on initial review. Otherwise looks good!

2022-01-12 09:13 UTC, mpetuska commented on kmdc/kmdc-menu-surface/src/jsMain/kotlin/MDCMenuSurfaceModule.kt
> +  public class MDCMenuSurfaceClosingEvent : MDCEvent<MDCMenuSurfaceEventDetail>
These three events are identical and could be represented by a single MDCMenuSurfaceEvent class

2022-01-13 04:29 UTC, gsteckman commented on kmdc/kmdc-menu-surface/src/jsMain/kotlin/MDCMenuSurfaceModule.kt
> +  public class MDCMenuSurfaceClosingEvent : MDCEvent<MDCMenuSurfaceEventDetail>
Yes, I thought about that too, but went the other way. I really don't have a strong argument for one approach or the other so reduced it to 1 event class if that's what you prefer.

2022-01-13 09:49 UTC, mpetuska approved these changes
And we're done! Thanks for your contribution.

2022-01-13 09:49 UTC, merged