kmdc-select (#22)
mpetuska/kmdc pull request #80
Opened 2022-01-29 13:26 UTC by Kiryushin-Andrey

2022-01-29 13:43 UTC, mpetuska requested changes
Hi, thanks for the contribution.

I started reviewing it, but noticed that general style and structure of kmdc is not followed very well (understandable as it's poorly documented in the first place). Could you have a look at some of the latest kmdc components and see if you can get a better feel of the architecture of the components (e.g. [kmdc-slider](https://github.com/mpetuska/kmdc/tree/master/kmdc/kmdc-slider)). After that, see if you can better refactor you component to match it.

2022-01-29 13:43 UTC, mpetuska commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +  internal class MDCSelect(element: Element) {
Make it extend MDCComponent from kmdc-core module

2022-01-29 13:43 UTC, mpetuska commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +  internal class MDCSelect(element: Element) {
Since the module is public, make this public too.

2022-01-29 13:43 UTC, mpetuska commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +@JsModule("@material/select/constants")
Aren't these re-exported in @material/select index.ts file? This separation is only to be used when constants cannot be reached via the index.ts file

2022-01-29 13:43 UTC, mpetuska commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +internal external object MDCSelectHelperTextModule {
Same as above, would be good to capture as much of the required exports from the index.ts as we can

2022-01-29 13:43 UTC, mpetuska commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +  class MDCSelectHelperText(element: Element) {
Should extend MDCComponent

2022-01-29 13:43 UTC, mpetuska commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +  public enum class Type(public vararg val classes: String) {
Is either of these classes required for the component to work? Does it have a "Default" state?

2022-01-29 13:43 UTC, mpetuska commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +  public enum class Type(public vararg val classes: String) {
This looks to be a wrong use-case for an enum seeing as values just append each other. Replace it with boolean flags instead.

2022-01-29 13:43 UTC, mpetuska commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +public class MDCSelectLeadingIconScope
Shouldn't it extend some ElementScope<T> ?

2022-01-29 13:43 UTC, mpetuska commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +public data class MDCSelectItem(val value: String, val text: String, val disabled: Boolean = false)
This should be a composable tied to MDCSelectScope instead

2022-01-29 13:43 UTC, mpetuska commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +      ref {
Once all MDC components extend MDCComponent, this entire ref block can be replaced with `initialiseMDC` call

2022-01-29 13:43 UTC, mpetuska commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +        items.forEach { item ->
This bit here should be replaced with invocation of `item` builder argument to be added above, which takes value and expects the end user to build an item.

2022-01-29 13:43 UTC, mpetuska commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +private fun mdcSelectDropdownIcon() {
Composables should start in upper case

2022-01-29 13:43 UTC, mpetuska commented on sandbox/src/jsMain/kotlin/samples/Select.kt
> +private val SelectSamples = Samples("MDCSelect") {
This should call delegate instead of assigning it - `by` instead of `=`

2022-01-29 14:20 UTC, Kiryushin-Andrey commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +        items.forEach { item ->
It was my initial design, but I stumbled over the need to provide selected text earlier in the composable tree (see line 215) and it was not quite clear how to achieve this with items represented by composable functions... Do you have any ideas?

2022-01-29 14:20 UTC, Kiryushin-Andrey commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +        items.forEach { item ->
That was my initial design, but I stumbled over the need to provide selected text for the

2022-01-29 14:44 UTC, mpetuska commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +        items.forEach { item ->
This is normally achieved by three arguments:
1. `selected: T`
2. `items: List<T>`
3. `renderItem: (T) -> Unit`

2022-01-29 18:40 UTC, Kiryushin-Andrey commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +  public enum class Type(public vararg val classes: String) {
Yep, either one or another is required, there's no default variant (the component layout is broken without any of those classes).

2022-01-29 19:11 UTC, Kiryushin-Andrey commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +  public enum class Type(public vararg val classes: String) {
I'm not sure boolean flags is a good choice here - not any combination of the flags would be meaningful. For example, having `persistentValidation = true` and `validation = false` wouldn't make much sense. Only those combinations of the classes listed in enum values are meaningful.

2022-01-29 21:52 UTC, Kiryushin-Andrey commented on sandbox/src/jsMain/kotlin/samples/Select.kt
> +private val SelectSamples = Samples("MDCSelect") {
It doesn't compile with delegating - type `Samples` has no method `getValue`. And all the other samples are assigned, not delegated.

2022-01-30 14:24 UTC, Kiryushin-Andrey commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +        items.forEach { item ->
I reworked the component interface this way, and for consistency the `onChange` event now also represents the selected item as an instance of T instead of a plain string value. This change has required the event handler to know the list of items (to convert from string value to a T instance), that isn't currently possible to wrap with an `AttrsBuilder` because of https://github.com/JetBrains/compose-jb/issues/1651. That's why I moved the event handler from attrs to options, though this isn't an idiomatic place for a component event handler.

2022-01-30 14:25 UTC, Kiryushin-Andrey commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +  internal class MDCSelect(element: Element) {
Done

2022-01-30 14:25 UTC, Kiryushin-Andrey commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +  internal class MDCSelect(element: Element) {
Done

2022-01-30 14:26 UTC, Kiryushin-Andrey commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +@JsModule("@material/select/constants")
Yep, they are, fixed this

2022-01-30 14:26 UTC, Kiryushin-Andrey commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +internal external object MDCSelectHelperTextModule {
Done

2022-01-30 14:26 UTC, Kiryushin-Andrey commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +  class MDCSelectHelperText(element: Element) {
Done

2022-01-30 14:31 UTC, Kiryushin-Andrey commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +public class MDCSelectLeadingIconScope
I don't think so, since I wouldn't like to allow anything but an `MDCSelectLeadingIcon` call here. The only pieces that are expected to be configurable here are the css classes and the content of the `i` tag that together make up an icon. Any other markup will likely break the component's layout. Given that, maybe it's worth having a `LeadingIcon` property with icon name and css class in it in component's options instead of providing a configuration lambda, WDYT?

2022-01-30 14:31 UTC, Kiryushin-Andrey commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +public data class MDCSelectItem(val value: String, val text: String, val disabled: Boolean = false)
Reworked it to a triple of `items`, `options.value` and `renderItem`

2022-01-30 14:31 UTC, Kiryushin-Andrey commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +      ref {
Done

2022-01-30 14:32 UTC, Kiryushin-Andrey commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +private fun mdcSelectDropdownIcon() {
Fixed

2022-01-31 09:27 UTC, mpetuska commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +        classes(*helperText.type.classes)
@sonatype-lift ignore

2022-01-31 13:01 UTC, mpetuska requested changes
Much better this time around, but there still are some bits I'd like polished.

2022-01-31 13:01 UTC, mpetuska commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +  var helperText: MDCSelectHelperText? = null
Nesting should be avoided in opts. Let's have `helperText` & `helperType` variables instead.

2022-01-31 13:04 UTC, mpetuska commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +        items.forEach { item ->
This is still iffy from API consistency perspective. You could "store" the items list on the `mdc` object and retrieve it that way without having to keep event handling code inside the MDC component

2022-02-01 09:09 UTC, mpetuska commented
I appreciate this might be sucking up more time than you are ready to spare, so I can offer to merge this PR as-is for now and then I'll raise another PR with the remaining polishes for you to review and get a better sense of the general direction kmdc is going for.

2022-02-01 19:10 UTC, Kiryushin-Andrey commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +        items.forEach { item ->
Neat trick! That didn't occur to me. Done, works fine (although worth revisiting after `AttrsBuilder` is an interface imo)

2022-02-01 19:12 UTC, Kiryushin-Andrey commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +public class MDCSelectLeadingIconScope
I got rid of this scope altogether, leading icon is now set up via options

2022-02-01 19:12 UTC, Kiryushin-Andrey commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +  var onChange: ((value: T) -> Unit)? = null,
done

2022-02-01 19:13 UTC, Kiryushin-Andrey commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +  public fun <S> copyFrom(source: MDCSelectOpts<S>, map: S.() -> T, unmap: T.() -> S) {
dropped, and overall simplified the component interface regarding its generic type parameter (no more `MDCSelectItem` constraint, I added `itemValue` and `itemDisabled` lambdas to options instead)

2022-02-01 19:13 UTC, Kiryushin-Andrey commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +    Validation(*(Default.classes + "mdc-select-helper-text--validation-msg")),
done

2022-02-01 19:13 UTC, Kiryushin-Andrey commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +  val labelId = remember { uniqueDomElementId() }
done

2022-02-01 19:19 UTC, Kiryushin-Andrey commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +  opts: Builder<MDCSelectOpts<T>>? = null,
I think items are quite handy as a first argument: The main point is that having them right here and not within the options enables for type parameter inference on `MDCSelect` function call - if we put items into options, we'll force the callers to always specify the type parameter explicitly, which is kind of verbose.
The items are always present and are arguably the most important argument for the select component, so it's also rather expected to have them before opts.  I also actually see a number of such "lifted" arguments in other components of the library, like for example `value` in `MDCTextArea` or `checked` in `MDCCheckbox` (but that might be an outdated pattern, idk).

2022-02-01 19:19 UTC, Kiryushin-Andrey commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +        addEventListener(MDCSelectModule.strings.CHANGE_EVENT) {
done

2022-02-01 19:20 UTC, Kiryushin-Andrey commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +public fun <T : MDCSelectItem> MDCSelect(
Simplified this whole thing and left only one signature of `MDCSelect` which looks both handy and customizable enough to me

2022-02-01 19:21 UTC, Kiryushin-Andrey commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +  leadingIcon: ComposableBuilder<MDCSelectLeadingIconScope>? = null,
This scope is now gone in favor of 3 new properties in options

2022-02-01 19:21 UTC, Kiryushin-Andrey commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +  var helperText: MDCSelectHelperText? = null
done

2022-02-01 19:27 UTC, Kiryushin-Andrey commented
> I appreciate this might be sucking up more time than you are ready to spare, so I can offer to merge this PR as-is for now and then I'll raise another PR with the remaining polishes for you to review and get a better sense of the general direction kmdc is going for.

No worries, I have time to work on that, so I'm quite fine proceeding with this MR :)

2022-02-02 10:13 UTC, mpetuska commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +        items.forEach { item ->
I will in #62

2022-02-02 10:15 UTC, mpetuska commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +  opts: Builder<MDCSelectOpts<T>>? = null,
Fair point. Let's leave it as-is and see how it compares with the other components once we're closer to 0.1.0

2022-02-02 10:30 UTC, mpetuska requested changes
Few minor changes still, but I think after that I'll merge the PR in. I'm still uncertain about some of the new API, but it will have to be refined during the final API review just before 0.1.0 release. To be clear, this is not the only component with uncertain API so far 😆

2022-02-02 10:30 UTC, mpetuska commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +      initialiseMDC(mdcInit = {
You should use `postInit` argument for this
```
initialiseMDC(MDCSelectModule.MDCSelect::attachTo) {_, mdc ->
  it.items = items
}
```

2022-02-02 10:30 UTC, mpetuska commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +              MDCListItemGraphic()
`options.leadingIcon` seems to only be used as a boolean condition here. If that's the case, it should be converted to `Boolean = false` type

2022-02-02 10:30 UTC, mpetuska commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelectAnchor.kt
> +        classes(*it.toTypedArray())
@sonatype-lift ignore

2022-02-02 10:30 UTC, mpetuska commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelectAnchor.kt
> +      options.leadingIconClasses.takeUnless { it.isEmpty() }?.let {
`takeUnless { it.isEmpty() }` is redundant here. `classes()` already handles that

2022-02-02 10:30 UTC, mpetuska commented on kmdc/kmdc-select/src/jsMain/kotlin/events.kt
> +    (it.nativeEvent.currentTarget as? Element)
`it.nativeEvent.currentTarget as? Element` could be simplified with `event.currentTarget as? Element`

2022-02-02 14:49 UTC, Kiryushin-Andrey commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +      initialiseMDC(mdcInit = {
Done - but I'm not able to use function reference here anyway, because `MDCSelect` class and `attachTo` function are generic:

```
      initialiseMDC(
        mdcInit = { MDCSelectModule.MDCSelect.attachTo<T>(it) },
        postInit = { _, mdc -> mdc.items = items }
      )
```

2022-02-02 14:49 UTC, Kiryushin-Andrey commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +              MDCListItemGraphic()
It's used as icon name in `MDCSelectAnchor`

2022-02-02 14:51 UTC, Kiryushin-Andrey commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelectAnchor.kt
> +      options.leadingIconClasses.takeUnless { it.isEmpty() }?.let {
fixed

2022-02-02 14:51 UTC, Kiryushin-Andrey commented on kmdc/kmdc-select/src/jsMain/kotlin/events.kt
> +    (it.nativeEvent.currentTarget as? Element)
done

2022-02-02 15:02 UTC, mpetuska approved these changes
Nice one. Thanks for the contribution 🎉

2022-02-02 15:10 UTC, merged