kmdc-dialog (#11)
mpetuska/kmdc pull request #81
Opened 2022-01-29 13:36 UTC by Kiryushin-Andrey

2022-02-02 11:04 UTC, mpetuska requested changes
Looks good, but there are few minor things that needs some polish.

2022-02-02 11:04 UTC, mpetuska commented on kmdc/kmdc-dialog/src/jsMain/kotlin/events.kt
> +public fun MDCDialogAttrsScope.onOpening(listener: () -> Unit) {
Just to check, does mdc not have any event details for opening and opened events?

2022-02-02 11:04 UTC, mpetuska commented on sandbox/src/jsMain/kotlin/samples/Dialog.kt
> +private fun AlertDialog() {
No need to change it, but there is some [syntax sugar](https://github.com/mpetuska/kmdc/blob/master/sandbox/src/jsMain/kotlin/samples/SegmentedButton.kt#L35) for such sample separation. Could be expressed as `val Alert by Sample { ... }`

2022-02-05 17:16 UTC, Kiryushin-Andrey commented on kmdc/kmdc-dialog/src/jsMain/kotlin/MDCDialog.kt
> +  val headerId = remember { uniqueDomElementId() }
You probably meant `titleId` in `MDCDialogScope` - yep, the proper name is `titleId`, fixed

2022-02-05 17:16 UTC, Kiryushin-Andrey commented on kmdc/kmdc-dialog/src/jsMain/kotlin/MDCDialog.kt
> +      it.mdc<MDCDialogModule.MDCDialog> { it.mdc<MDCDialogModule.MDCDialog> { if (options.open) open() else close("") } }
sure :)

2022-02-05 17:17 UTC, Kiryushin-Andrey commented on kmdc/kmdc-dialog/src/jsMain/kotlin/MDCDialogHeader.kt
> +      classes("mdc-dialog__close", "material-icons")
fixed

2022-02-05 17:18 UTC, Kiryushin-Andrey commented on kmdc/kmdc-dialog/src/jsMain/kotlin/MDCDialogTitle.kt
> +public fun MDCDialogHeaderScope.MDCDialogTitle(
I'm not sure it's worth doing, because in this case all the extension functions for `MDCDialogScope` will become available in the header scope, allowing for invalid hierarchies like header in header, or content in header.

2022-02-05 17:19 UTC, Kiryushin-Andrey commented on kmdc/kmdc-dialog/src/jsMain/kotlin/MDCDialogTitle.kt
> +public fun MDCDialogScope.MDCDialogTitle(
Done

2022-02-05 17:20 UTC, Kiryushin-Andrey commented on kmdc/kmdc-dialog/src/jsMain/kotlin/events.kt
> +public fun MDCDialogAttrsScope.onOpening(listener: () -> Unit) {
The doc specifies those details as empty object. However, for consistensy and for the event listener to be able to access the original event object (to get target or control propagation, for example), it's probably still worth passing an event object to the listener - I added the parameter here.

2022-02-05 17:27 UTC, Kiryushin-Andrey commented on sandbox/src/jsMain/kotlin/samples/Dialog.kt
> +private fun AlertDialog() {
Nice syntax, made use of it

2022-02-05 19:31 UTC, mpetuska approved these changes
Once again, thanks for your contribution!

2022-02-05 19:31 UTC, merged