Recreate MDCSelect when changing the items list to fix behavior.
mpetuska/kmdc pull request #91
Opened 2022-02-21 01:23 UTC by gsteckman

After component creation, if the items list was changed and contained different values and/or a different length from the list used at creation, a change event with an incorrect index (e.g. -1) would be fired causing an exception and errant behavior. 

During initialization, the material-components-web MDCSelect class builds a list of items based on elements with the data-value attribute. When the items change, this list isn't recreated. The fix in this PR destroys the existing MDCSelect object and creates a new instance whenever the items change, causing the new MDCSelect object to be initialized based on the element tree created from the new items list.

2022-02-21 12:19 UTC, mpetuska requested changes

2022-02-21 12:19 UTC, mpetuska commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +        destroy()
Shouldn't this be moved to `onDispose{}`

2022-02-21 12:19 UTC, mpetuska commented on kmdc/kmdc-select/src/jsMain/kotlin/events.kt
> +          console.warn("MDCSelect component - index -1 for change event")
The message is not very useful. Maybe add a sentence explaining why -1 is bad?

2022-02-22 02:58 UTC, gsteckman commented on kmdc/kmdc-select/src/jsMain/kotlin/MDCSelect.kt
> +        destroy()
Yes, good catch. This DisposableEffect(items) can then also become the one place where the MDCSelect object is created and disposed of.

2022-02-22 08:18 UTC, mpetuska approved these changes

2022-02-22 08:18 UTC, merged